### PR TITLE
Themes (cupertino): Set individual selectors

### PR DESCRIPTION
**Pull request by jonaaix**
Individual selectors as suggested

### CODE REVIEW

**Comment by antelle** [comment]
Done, they're published

**Comment by jonaaix** [comment]
Another question:
While developing in chrome, `backdrop-filter: blur(20px);` worked fine. However it seems to be not supported in the current electron build. Can we enable this if possible?

**Comment by antelle** [comment]
I'm not sure if it's possible, do you know how to enable it in Electron?

**Comment by antelle** [comment]
Did you expect the window to become [vibrant](https://www.electronjs.org/docs/api/browser-window#winsetvibrancytype-macos)? You can try calling this API, maybe it will work.

**Comment by jonaaix** [comment]
According to [this](https://discuss.atom.io/t/backdrop-filter-compatibility-in-electron/33280/2), it needs

```js
webPreferences: {
    experimentalFeatures: true
}

```
Might this be a security issue?
The vibrant API looks also interesting, the `backdrop-filter` just makes popups and dropdowns blurry transcluent:

**Comment by jonaaix** [comment]
Update: I just switched between some themes, and suddenly it got working for me. Possibly really still "experimental"

**Comment by antelle** [comment]
Then it means that we'll have to wait until it reaches a stable release. Enabling experimental features is not the right thing to do in terms of security: https://www.electronjs.org/docs/tutorial/security#8-do-not-enable-experimental-features

**Pull request merged**
