### PR TITLE
Dracula Theme constrast

### PR DESCRIPTION
**Pull request by 0xNeffarion**
Fixed the contrast on some menus and buttons. Added some shadows to the icons, so it's a bit easier to see as well

### CODE REVIEW

**Comment by antelle** [comment]
Hi! Thanks 🎁 
Merged in 85c4a3264b2d404baa71b8aad477bbaae6b54699, don't forget to pull master and bump the version 😉

**Comment by antelle** [comment]
Ouch... some selectors are missing the theme name, they were applied outside of this theme, fixed in fe9aa6c201810d7c41c90c047ac9c382c77e94c5

**Comment by antelle** [comment]
Now this is fixed, however buttons are sad:

Screen Shot 2021-03-22 at 23 13 43

**Comment by 0xNeffarion** [comment]
My bad, didnt see that, ill do another pull

**Pull request closed without merging**
