### PR TITLE
Replace the alerts and trimed the logs

### PR DESCRIPTION
**Pull request by leolivier**
Hi @antelle 
As suggested, I replaced the alerts by an animated icon and a tip when hovering the icon.
Also I replaced most of the "Info" logging by "Debug" logging, the default level is Info.

I tested it on Firefox and Chrome but I can't find a way for testing it in the desktop application. Any hint on this?

### CODE REVIEW

**Comment by antelle** [comment]
Cool, I've updated it.
It looks like this though:
plugin
I'd suggest using themed classes instead of hard-coded colors: `error-color`, `background-color`, and so on, they will be changed with theme changes. Also you can use css properties, like `--error-color`, keeweb doesn't work in browsers without css variables support.

**Comment by antelle** [comment]
About testing in desktop apps, you can host your plugin and load it there. E.g. with
```
keeweb-plugin watch <path>
```

**Comment by leolivier** [comment]
In order to use the error-color variable as suggested, I tried using an scss file instead of the css one in my plugin.
I changed the name from plugin.css to plugin.scss and I replaced the "css" line by "scss" in the manifest.json file and tried to sign. It didn't work (and couldn't as I realized in reading the keeweb-plugin code)
So I tried to revert and I'm now constantly experiencing an error when the plugin loads:
```
2018-03-25T16:52:25.284Z [plugin:haveibeenpwned] Resource signature invalid js
127.0.0.1:8089:1:1212
2018-03-25T16:52:25.284Z [plugin:haveibeenpwned] Error validating resource signature js
127.0.0.1:8089:1:1212
2018-03-25T16:52:25.284Z [plugin:haveibeenpwned] Error installing plugin Error loading plugin resources
127.0.0.1:8089:1:1212
2018-03-25T16:52:25.294Z [app] Error starting app Error loading plugin resources
127.0.0.1:8089:1:1212
2018-03-25T16:52:25.294Z [plugin:haveibeenpwned] Resource signature invalid css
127.0.0.1:8089:1:1212
2018-03-25T16:52:25.296Z [plugin:haveibeenpwned] Error validating resource signature css
127.0.0.1:8089:1:1212
```

Although the keeweb-plugin sign command is ok:
```
olivier@baloo-17 ~/apps/keeweb-plugins/docs/plugins $ keeweb-plugin sign haveibeenpwned 
KeeWeb plugin utils v0.1.11
Signing js...
Signing css...
Done, package manifest updated
```

I tried putting js and css to true in the manifest.json before retrying signing but no way :/
So I can't start my plugin anymore...
Should I recreate it from scratch?

**Comment by antelle** [comment]
1. css: you don't need scss for this, they're defined as [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) in `body`, you can use `color: var(--error-color)`. 
2. signature: I've updated your signature in plugin manifest, so in order to use it again, you need to put `publicKey` back (you can replace it from git). Probably in dev mode, we don't need to validate signatures at all, to make it easier.

**Comment by leolivier** [comment]
cool, I didn't know about css variables... Looked for this for years!
I deliver the modified css soon...

**Pull request merged**
